### PR TITLE
Add CMakeLists.txt

### PR DESCRIPTION
**Pull request by pdimov**
uBLAS is one of the two remaining Boost libraries still missing CMake support. This adds it.

### CODE REVIEW

**Comment by lordjaxom** [comment]
Will this be merged anytime soon?

**Comment by greg7mdp** [comment]
Please merge this PR. It is required for `ublas` to be usable when boost is added as a submodule to a project.

**Comment by pdimov** [comment]
At the moment `ublas` is the only Boost library lacking a CMakeLists.txt, which creates problem for Boost users who use CMake (https://github.com/boostorg/cmake/issues/41 is the latest instance of this being brought up.)

What needs to be done to get this merged?

**Comment by q-ycong-p** [comment]
Would really appreciate if reviewer(s) can take a look at this PR! Checking out this patch locally unblocks me from using CMake with Boost. It would saved much trouble if merged. Ty!

**Comment by jdumas** [comment]
@bassoy any update on this PR? I am also running into this issue when trying to build Boost from source via CMake.

**Comment by pdimov** [comment]
I've just received another complaint that `Boost::accumulators` isn't functional because it depends on `Boost::numeric_ublas`, and uBlas does not have a CMakeLists.txt. (https://github.com/boostorg/cmake/issues/45#issuecomment-1815966205)

Since I see no activity here, if I receive no complaints, I will go ahead and add the CMakeLists.txt file to both master and develop, so that CMake users of Accumulators (and uBlas itself, for that matter) can be unblocked.

**Comment by greg7mdp** [comment]
haha, about time! Thanks Peter.

**Comment by jdumas** [comment]
I think the CMakeLists looks good and I'd be happy to see it merged as well.

**Comment by lordjaxom** [comment]
+1

**Comment by amitsingh19975** [comment]
@bassoy should I merge this, or does anyone else want to do? If anyone has any objection, say no.

**Review by amitsingh19975 — APPROVED** [review]
It looks.

**Pull request closed without merging**
